import { line, blank, section, linkLine, ascii, success, error, muted } from './helpers.js';

export const helpCommand = {
  name: 'help',
  aliases: ['h', '?'],
  description: 'List all available commands',
  execute: () => [
    blank(),
    section('┌─ AVAILABLE COMMANDS ─────────────────────────────────┐'),
    blank(),
    line('  about         →  Professional summary & background', 'info'),
    line('  skills        →  Tech stack grouped by category', 'info'),
    line('  experience    →  Work history', 'info'),
    line('  projects      →  List projects  |  projects <name>', 'info'),
    line('  education     →  Degree info', 'info'),
    line('  contact       →  Contact info & social links', 'info'),
    line('  achievements  →  Awards, certs & extracurriculars', 'info'),
    line('  resume        →  Download resume PDF', 'info'),
    blank(),
    line('  clear         →  Clear the terminal', 'info'),
    line('  theme <name>  →  Switch theme (green|amber|matrix|solarized)', 'info'),
    line('  sound on|off  →  Toggle keystroke sounds', 'info'),
    line('  crt           →  Toggle CRT scanline effect', 'info'),
    blank(),
    section('  ★  EASTER EGGS'),
    line('  whoami        →  ???', 'info'),
    line('  matrix        →  Enter the Matrix', 'info'),
    line('  coffee        →  I need this', 'info'),
    line('  sudo hire-me  →  Make an offer', 'info'),
    blank(),
    section('└───────────────────────────────────────────────────────┘'),
    blank(),
    muted('  Tip: use ↑/↓ for history, Tab to autocomplete'),
    blank(),
  ],
};
